### ISSUE TITLE
FromPrimitive

### ISSUE THREAD

**Issue by MarkSwanson** [japaric/simplot.rs#35]
FromPrimitive has been moved to the external 'num' create.
I took a stab at creating a patch for you but rust seems to disregard my
use num::FromPrimitive

as it still thinks the num trait is a non-existent std::num::FromPrimitive???

The compile error for this enum:
#[derive(Clone, Copy, FromPrimitive)]
pub enum Grid {
/// Major gridlines
Major,
/// Minor gridlines
Minor,
}

is: use of undeclared trait name std::num::FromPrimitive

**Comment by japaric** [comment]
Thanks for the report, I have updated `simplot` to work with the latest nightly. (btw, I stopped using FromPrimitive altogether)

**Comment by MarkSwanson** [comment]
Nice work!
I'm using it through criterion.rs and it's working perfectly atm.
